#ifndef SW_V5_S5_CONTRACTS_MQH
#define SW_V5_S5_CONTRACTS_MQH

// SPRINT 5 PHASE B CANDIDATE UMBRELLA
// PURE CONTRACTS ONLY / NOT RUNTIME AUTHORIZATION

#include "SW_V5_S5_OrchestrationContract.mqh"

#endif
